// react/storybook-v6/src/components/Button.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { chevronRightIcon } from './icons';
import { ReactSVG } from 'react-svg';

import './_button.scss';

/**
 * Buttons indicate actions on the page that will occur when a user touches them. This button is responsive to screen sizes.
 * We support a very minimal level of variation for the primary button. Custom styling or class names should not be applied to the primary button.
 * It requires text in all cases, but allows for icons as an optional addition.
 * The primary button can also exist as an element within larger molecules and organisms.
 * */
const Button = ({ onClick, icon, disabled, children }) => {
  return (
    <button
      onClick={!disabled && onClick}
      className={`c-button ${icon && 'c-button__with-icon'} ${disabled && 'c-button__disabled'}`}
    >
      <div className="c-button__content">{children}</div>
      {icon && (
        <div className="c-button__icon">
          <ReactSVG src={chevronRightIcon} />
        </div>
      )}
    </button>
  );
};

Button.propTypes = {
  /**
   * Adds an icon to the button
   */
  icon: PropTypes.oneOf(['chevron-right']),
  /**
   * The content of the Button
   * */
  children: PropTypes.node,
  /**
   * Disable state of the button
   * */
  disabled: PropTypes.bool,
  /**
   * The function to be called when the button is clicked
   */
  onClick: PropTypes.func
};

Button.defaultProps = {
  disabled: false
};

export default Button;

// angular/storybook-v5/src/app/components/button/button.component.ts
import { Component, EventEmitter, Input, Output, ViewEncapsulation } from '@angular/core';

/**
 * Buttons indicate actions on the page that will occur when a user touches them. This button is responsive to screen sizes.
 * We support a very minimal level of variation for the primary button. Custom styling or class names should not be applied to the primary button.
 * It requires text in all cases, but allows for icons as an optional addition.
 * The primary button can also exist as an element within larger molecules and organisms.
 * */
@Component({
  selector: 'button[dsm-button]',
  host: {
    class: 'c-button',
    '[class.disabled]': 'disabled',
    '[class.with-icon]': "(icon !== 'none')",
    '(click)': '!disabled && action()'
  },
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class ButtonComponent {
  icons = {
    'chevron-right': 'chevronRightIcon'
  };

  /**
   * The content of the Button
   * */
  @Input()
  text: string = '';

  /**
   * Disable state of the button
   * */
  @Input()
  disabled: boolean = false;

  /**
   * Adds an icon to the button
   */
  @Input()
  icon: 'none' | 'chevron-right' = 'none';

  /**
   * The function to be called when the button is clicked
   */
  @Output()
  didClick = new EventEmitter<void>();

  action() {
    this.didClick.emit();
  }
}

<button [ngClass]="{'c-button': true, 'c-button__disabled': disabled, 'c-button__with-icon': icon !== 'none'}"
        (click)="!disabled && action && action()">
  <div class="c-button__content">
    {{ text }}
  </div>
  <div *ngIf="icon !== 'none'" class="c-button__icon-container">
    <app-icons class="c-button__icon" [icon]="icons[icon]"></app-icons>
  </div>
</button>
