// react/storybook-v4/src/components/Button.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { chevronRightIcon } from './icons';
import SVGInline from 'react-svg-inline';

import './_button.scss';

/**
 * Buttons indicate actions on the page.
 * */
const Button = ({ onClick, icon, disabled, children }) => {
  return (
    <button
      onClick={!disabled && onClick}
      className={`c-button ${icon && 'c-button__with-icon'} ${disabled && 'c-button__disabled'}`}
    >
      <div className="c-button__content">{children}</div>
      {icon && (
        <div className="c-button__icon">
          <SVGInline svg={chevronRightIcon} />
        </div>
      )}
    </button>
  );
};

Button.propTypes = {
  /**
   * Adds an icon to the button
   */
  icon: PropTypes.oneOf(['chevron-right']),
  /**
   * The content of the Button
   * */
  children: PropTypes.node,
  /**
   * Disable state of the button
   * */
  disabled: PropTypes.bool,
  /**
   * The function to be called when the button is clicked
   */
  onClick: PropTypes.func
};

Button.defaultProps = {
  disabled: false
};

export default Button;

// angular/storybook-v4/src/app/components/button/button.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

/**
 * Buttons indicate actions on the page.
 * */
@Component({
  selector: 'button-component',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss']
})
export class ButtonComponent {
  icons = {
    'chevron-right': 'chevronRightIcon'
  };

  /**
   * The content of the Button
   * */
  @Input()
  text: string = '';

  /**
   * Disable state of the button
   * */
  @Input()
  disabled: boolean = false;

  /**
   * Adds an icon to the button
   */
  @Input()
  icon: 'none' | 'chevron-right' = 'none';

  /**
   * The function to be called when the button is clicked
   */
  @Output()
  didClick = new EventEmitter<void>();

  action() {
    this.didClick.emit();
  }
}

<button [ngClass]="{'c-button': true, 'c-button__disabled': disabled, 'c-button__with-icon': icon !== 'none'}"
        (click)="!disabled && onClick && onClick()">
  <div class="c-button__content">
    {{ text }}
  </div>
  <div *ngIf="icon !== 'none'" class="c-button__icon-container">
    <app-icons class="c-button__icon" [icon]="icons[icon]"></app-icons>
  </div>
</button>
