// angular/storybook-v6/src/app/components/toast/toast.component.ts
import { Component, Input } from '@angular/core';

/**
 * Toasts provide dismissable feedback\information for the user.
 * */
@Component({
  selector: 'toast-component',
  templateUrl: './toast.component.html',
  styleUrls: ['./toast.component.scss']
})
export class ToastComponent {
  icons = {
    default: 'flagIcon',
    warning: 'warnIcon',
    success: 'checkmarkIcon',
    error: 'errorIcon',
    info: 'infoIcon'
  };

  /**
   * The content of the toast
   * */
  @Input()
  text: string;

  /**
   * Changes the visual display of the toast
   * */
  @Input()
  status: 'default' | 'warning' | 'error' | 'info' | 'success' = 'default';
}

// react/storybook-v6/src/components/Toast.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { CloseIcon } from './icons';
import { toastIcons } from './icons/toast-icons';

import './_toast.scss';

/**
 * Toasts provide dismissable feedback\information for the user.
 * */
const Toast = ({ text, status }) => {
  const ToastIcon = toastIcons[status];

  return (
    <div key={status} className={`c-toast ${status}`}>
      <ToastIcon className={`c-toast__icon ${status}`} />
      <span className="c-toast__text">{text}</span>
      <CloseIcon className="c-toast__close-icon" />
    </div>
  );
};

Toast.propTypes = {
  /**
   * Changes the visual display of the toast
   * */
  status: PropTypes.oneOf(['default', 'warning', 'error', 'info', 'success']),
  /**
   * The content of the toast
   * */
  text: PropTypes.string
};

Toast.defaultProps = {
  status: 'default'
};

export default Toast;
